### PR TITLE
Add instructions

### PR DESCRIPTION
**Pull request by kagia**
added instructions to be used after cloning repo

### CODE REVIEW

**Comment by andela-anandaa** [comment]
Could you fix the failing 'tests'?

**Comment by kagia** [comment]
I can't seem to access the settings for our project on StyleCi.

**Comment by andela-anandaa** [comment]
Set the configurations in the `.circle.yml` file. And just realized that you named the file wrongly, didn't put the dot (.) at the beginning.

**Comment by andela-anandaa** [comment]
@andela-bkagia @andela-sachungo - hey, sorry about the confusion on my last comment. the `circle.yml` file is okay. You are supposed to have a `.styleci.yml` file, starts with a dot. Check the [StyleCI docs](https://styleci.readme.io/)

**Pull request merged**
